package dto.CreateApplication.ProfileInfoFlecs;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
@Data
public class ApplicationProfile {
    private String constantId;
    private String appId;
    private String leadId;
    private String firstName;
    private String lastName;
    private String middleName;
    private String sex;
    private String passportBirthDate;
    private String passportBirthPlace;
    private String passportSeriesNumber;
    private String passportIssueDate;
    private String passportOfficeCode;
    private String passportOffice;
    private String passportSeriesNumberOld;
    private Boolean isNameChanged;
    private String previousFirstName;
    private String previousLastName;
    private String previousMiddleName;
    private String mobilePhone;
    private String code911;
    private String code911Comment;
    private int income;
    private String email;
    private String education;
    private String odeWord;
    private Boolean isForeignTaxResident;
    private String workRegionCode;
    private String workCompanyName;
    private String workCompanyInn;
    private String clientInn;
    private String employmentType;
    private String employmentTypeDescription;
    private String workPost;
    private String workPhone;
    private String registrationCountry;
    private String registrationZip;
    private String registrationRegionTypeCode;
    private String registrationRegionCode;
    private String registrationAreaCode;
    private String registrationAreaName;
    private String registrationCityName;
    private String registrationSettlementCode;
    private String registrationSettlementName;
    private String registrationStreetCode;
    private String registrationStreetName;
    private String registrationHouse;
    private String registrationBuilding;
    private String registrationFlat;
    private String registrationAddressPhone;
    private Boolean isAddressEquals;
    private String residenceCountry;
    private String residenceZip;
    private String residenceRegionTypeCode;
    private String residenceRegionCode;
    private String residenceAreaCode;
    private String residenceAreaName;
    private String residenceCityName;
    private String residenceSettlementCode;
    private String residenceSettlementName;
    private String residenceStreetCode;
    private String residenceStreetName;
    private String residenceHouse;
    private String residenceBuilding;
    private String residenceFlat;
    private String actualAddressPhone;
    private String cardCategory;
    private String cardType;
    private String cardTypeCode;
    private String cardDeliveryType;
    private String cardDeliveryTypeCode;
    private int loanSum;
    private String loanSumRecommended;
    private Boolean isAcceptedLimitEnabled;
    private String loanCurrency;
    private double creditPercent;
    private String loanBranch;
    private String branchMnemonic;
    private String branchCity;
    private String branchCityCode;
    private String branchAddress;
    private String loanCredType;
    private String loanProdCode;
    private int cardMaximumLimit;
    private String gracePeriod;
    private String delayedGracePeriod;
    private float commissionCashWithdrawal;
    private String clientEqId;
    private String clientCategoryCode;
    private String embossingName;
    private String mainIncomeAprMethod;
    private String cardPaySysCode;
    private String maritalStatus;
    private String spouseFirstName;
    private String spouseLastName;
    private String spouseMiddleName;
    private String spouseBirthDate;
    private String spousePhone;
    private String contactFirstName;
    private String contactLastName;
    private String contactMiddleName;
    private String contactPhone;
    private Boolean smartRepeat;
    private String stage;
    private Boolean isAddFieldsFilled;
    private Boolean isBalanceTransferRequired;
    private Boolean basicEs;
    private Boolean isInsuranceAvailable;
    private String cardTitle;
    private int codeWordLength;
    private String codeWord;
    private String branchName;
    private String bonusNumber;
    private Boolean basicEsEnabled;
    private String creationDate;
    private List<Document> docs = new ArrayList<>();
    private String wayToReceive;
    private List<BkiInfo> bkiInfos = new ArrayList<>();
    private String advertCode;
    private ApplicationTechInfo applicationTechInfo = new ApplicationTechInfo();
}
